# wrangler.toml
name = "viennaflow-landingpage"
main = "./src/api/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

routes = [
    { pattern = "viennaflow.at", custom_domain = true }
]

# Assets configuration if needed:
[assets]
binding = "ASSETS"
not_found_handling = "single-page-application"
