# wrangler.toml
name = "viennaflow-landingpage"
main = "./src/api/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

observability = { enabled = true }

assets = { binding = "ASSETS", directory = "./dist/client", not_found_handling = "single-page-application" }

[env.production]
routes = [
    { pattern = "viennaflow.at", custom_domain = true }
]

[env.preview]
name = "viennaflow-landingpage-preview"
routes = []
workers_dev = true


